/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package galge;

import server.GalgeInterf;
import server.GalgeLogik;

/**
 *
 * @author alexander
 */
public class View extends javax.swing.JFrame {
    
    private GalgeInterf g;

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }


    public void setGalgeLogik(GalgeInterf g){
        this.g=g;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_guess = new javax.swing.JLabel();
        button_guess = new javax.swing.JButton();
        text_guess = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_guess.setText("[Ordet]");

        button_guess.setText("GÆT");
        button_guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_guessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_guess)
                            .addComponent(label_guess)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(text_guess, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(label_guess)
                .addGap(34, 34, 34)
                .addComponent(text_guess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(button_guess)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_guessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_guessActionPerformed
        
        try{
          buttonPressed();
        } catch (java.rmi.RemoteException e){
            System.out.println("der er ikke forbindelse til serveren " + e );
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_button_guessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_guess;
    private javax.swing.JLabel label_guess;
    private javax.swing.JTextField text_guess;
    // End of variables declaration//GEN-END:variables

    
    private void buttonPressed() throws java.rmi.RemoteException {
        
        String str = text_guess.getText().toString().toLowerCase();
        g.gætBogstav(str);
        label_guess.setText(this.g.getOrd().toString());


    }
}


